mysite/ads/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='ads'
urlpatterns = [
    # http://127.0.0.1:8000/ads
    # Shows the list of ads (see class AdListView in ads/views.py)
    path('', views.AdListView.as_view(), name='all'),
    # http://127.0.0.1:8000/ads/ad/1 (1 is the number of the ad)
    # Shows the details of an ad (see class AdDetailView in ads/views.py)
    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),
    # http://127.0.0.1:8000/ads/ad/create
    # Creates a new ad and is handled by the class AdCreateView in ads/views.py
    path('ad/create',
        views.AdCreateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_create'),
    path('ad/<int:pk>/update',
        views.AdUpdateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_update'),
    path('ad/<int:pk>/delete',
        views.AdDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_delete'),
    path('ad_picture/<int:pk>', views.stream_file, name='ad_picture'),
    path('ad/<int:pk>/comment',
        views.CommentCreateView.as_view(), name='ad_comment_create'),
    path('comment/<int:pk>/delete',
        views.CommentDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_comment_delete'),
    path('ad/<int:pk>/favorite',
    # url to call the AddFavoriteView class in views.py
    views.AddFavoriteView.as_view(), name='ad_favorite'),
    # url to call the DeleteFavoriteView class in views.py
    path('ad/<int:pk>/unfavorite',
    views.DeleteFavoriteView.as_view(), name='ad_unfavorite'),
]

mysite/home/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

# Defines a namespace for the app
app_name = 'home'

urlpatterns = [
    # The page is defined in the home app in mysite/home/views.py
    # by the HomeView class
    # The name is used by the {% url %} template tag to generate the URL
    # for the page within the namespace defined in the app_name
    path('', views.HomeView.as_view(), name='home'),
]

mysite/mysite/urls.py
import os
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django.views.generic import TemplateView

urlpatterns = [
    # The line below defines the default page for the site
    # The exact page is defined in the home app in mysite/home/urls.py
    path('', include('home.urls', namespace='home')),
    path('admin/', admin.site.urls), 
    # This line includes the default authentication URLs provided by Django.
    # i.e. templates/registration directories in each app (in this case, home/templates/registration) 
    path('accounts/', include('django.contrib.auth.urls')), 
    # This line includes URLs for social authentication provided by the 
    # social_django package.
    # The re_path function is used for regular expression-based URL patterns. 
    # The pattern r'^oauth/' matches any URL that starts with 'oauth/'.
    # The include function includes the URLs defined in social_django.urls.
    # The namespace='social' parameter provides a namespace for these URLs, 
    # which can be useful for reversing URL patterns.
    re_path(r'^oauth/', include('social_django.urls', namespace='social')), 

    path('ads/', include('ads.urls')),
    path('autos/', include('autos.urls')),    
    path('cats/', include('cats.urls')),
    path('polls/', include('polls.urls')),
    path('hello/', include('hello.urls')),
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    re_path(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

# Switch to social login if it is configured
# in other words, if there is a file called github_settings.py
# Otherwise, use the default login template
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    # Insert the social_login view at the beginning of the list of URL patterns
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/4.2/ref/urls/#include

mysite/ads/forms.py
from django import forms
from ads.models import Ad
from django.core.files.uploadedfile import InMemoryUploadedFile
from ads.humanize import naturalsize
from django.core.exceptions import ValidationError


# strip means to remove whitespace from the beginning and the end before storing the column
class CommentForm(forms.Form):
    comment = forms.CharField(required=True, max_length=500, min_length=3, strip=True)
    
# Create the form class.
class CreateForm(forms.ModelForm):
    max_upload_limit = 2 * 1024 * 1024
    max_upload_limit_text = naturalsize(max_upload_limit)

    # Call this 'picture' so it gets copied from the form to the in-memory model
    # It will not be the "bytes", it will be the "InMemoryUploadedFile"
    # because we need to pull out things like content_type
    picture = forms.FileField(required=False, label='File to Upload <= '+max_upload_limit_text)
    upload_field_name = 'picture'

    # Hint: this will need to be changed for use in the ads application :)
    class Meta:
        model = Ad
        fields = ['title', 'text', 'price', 'tags', 'picture']  # Picture is manual

    # Validate the size of the picture
    def clean(self):
        cleaned_data = super().clean()
        pic = cleaned_data.get('picture')
        if pic is None:
            return
        if len(pic) > self.max_upload_limit:
            self.add_error('picture', "File must be < "+self.max_upload_limit_text+" bytes")
            
    # Convert uploaded File object to a picture
    def save(self, commit=True):
        instance = super(CreateForm, self).save(commit=False)

        # We only need to adjust picture if it is a freshly uploaded file
        f = instance.picture   # Make a copy
        if isinstance(f, InMemoryUploadedFile):  # Extract data from the form to the model
            bytearr = f.read()
            instance.content_type = f.content_type
            instance.picture = bytearr  # Overwrite with the actual image data

        if commit:
            instance.save()
            self.save_m2m()    # Add this

        return instance

# https://docs.djangoproject.com/en/4.2/topics/http/file-uploads/
# https://stackoverflow.com/questions/2472422/django-file-upload-size-limit
# https://stackoverflow.com/questions/32007311/how-to-change-data-in-django-modelform
# https://docs.djangoproject.com/en/4.2/ref/forms/validation/#cleaning-and-validating-fields-that-depend-on-each-other

mysite/ads/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse

# Create your views here.

from ads.models import Ad, Comment, Fav
from ads.owner import OwnerListView, OwnerDetailView, OwnerCreateView, OwnerUpdateView, OwnerDeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.urls import reverse_lazy, reverse
from ads.forms import CreateForm, CommentForm

from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.db.utils import IntegrityError
from django.contrib.humanize.templatetags.humanize import naturaltime
from django.db.models import Q


# class AdListViewT(OwnerListView):
#     model = Ad

# Note 1:
# The Vanilla class above shows the template and polulates it with the data
# but it only allows for a simple search. The class below allows for a more complex
# search and favorites handling, for example.

# Note 2:
# The view defined by this class as currently defined does not require the user to be logged in.
# Should you need it to require the user to be logged in, you could add an exta mixin to the class
# like so:  
#        class AdListView(LoginRequiredMixin, OwnerListView):
# and the view will get automagically redirected to the login page if the user is not logged in.

class AdListView(OwnerListView):
    model = Ad
    # By convention the template should be named as <model>_list.html
    # and placed in the templates/<app_name> directory
    template_name = "ads/ad_list.html"
    
    def get(self, request) :
        strval =  request.GET.get("search", False)
        if strval :
            # Simple title-only search
            # objects = Post.objects.filter(title__contains=strval).select_related().distinct().order_by('-updated_at')[:10]

            # Multi-field search
            # __icontains for case-insensitive search
            query = Q(title__icontains=strval) 
            query.add(Q(text__icontains=strval), Q.OR)
            ad_list = Ad.objects.filter(query).select_related().distinct().order_by('-updated_at')[:10]
        else :
            ad_list = Ad.objects.all().order_by('-updated_at')[:10]

        # Augment the ad_list
        for obj in ad_list:
            # Add a 'natural_updated' attribute to each object containing a friendly representation of the update time
            obj.natural_updated = naturaltime(obj.updated_at)
            
        if request.user.is_authenticated:
            # rows = [{'id': 2}, {'id': 4} ... ]  (A list of rows)
            rows = request.user.favorite_ads.values('id')
            # favorites = [2, 4, ...] using list comprehension
            favorites = [ row['id'] for row in rows ]
        else:
            favorites = []

        ctx = {'ad_list' : ad_list, 'search': strval, 'favorites': favorites}
        return render(request, self.template_name, ctx)
    

class AdDetailView(OwnerDetailView):
    model = Ad
    # By convention the template should be named as <model>_detail.html
    # and placed in the templates/<app_name> directory of the app.
    template_name = "ads/ad_detail.html"
    def get(self, request, pk) :
        # Get the ad object with the given primary key (pk)
        # If the object does not exist, return a 404 error
        x = get_object_or_404(Ad, id=pk)
        comments = Comment.objects.filter(ad=x).order_by('-updated_at')
        comment_form = CommentForm()
        context = { 'ad' : x, 'comments': comments, 'comment_form': comment_form }
        return render(request, self.template_name, context)

# class AdCreateView(OwnerCreateView):
#     model = Ad
#     # List the fields to copy from the Article model to the Article form
#     fields = ['title', 'price', 'text']
    
class AdCreateView(LoginRequiredMixin, View):
    """
    View for creating a new advertisement.

    This view requires the user to be logged in. It handles the GET and POST
    requests for creating a new advertisement. The GET request renders the
    form for creating a new ad, while the POST request processes the form data
    and saves the new advertisement if the data is valid.

    Attributes:
        None

    Methods:
        get(self, request, *args, **kwargs): Renders the form for creating a new ad.
        post(self, request, *args, **kwargs): Processes the form data and saves the new ad if valid.
    """
    
    template_name = 'ads/ad_form.html'
    success_url = reverse_lazy('ads:all')

    # The get method is used to display the empty form to be filled by the user
    def get(self, request, pk=None):
        # Define the fields to be displayed in the form
        form = CreateForm()
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        form = CreateForm(request.POST, request.FILES or None)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        # Add owner to the model before saving
        ad = form.save(commit=False)
        ad.owner = self.request.user
        ad.save()
        # https://django-taggit.readthedocs.io/en/latest/forms.html#commit-false
        form.save_m2m()    # Add this
        return redirect(self.success_url)


# class AdUpdateView(OwnerUpdateView):
#     model = Ad
#     fields = ['title', 'price', 'text']

    
class AdUpdateView(LoginRequiredMixin, View):
    template_name = 'ads/ad_form.html'
    success_url = reverse_lazy('ads:all')

    def get(self, request, pk):
        ad = get_object_or_404(Ad, id=pk, owner=self.request.user)
        form = CreateForm(instance=ad)
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        ad = get_object_or_404(Ad, id=pk, owner=self.request.user)
        form = CreateForm(request.POST, request.FILES or None, instance=ad)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        ad = form.save(commit=False)
        ad.save()
        # https://django-taggit.readthedocs.io/en/latest/forms.html#commit-false
        form.save_m2m()    # Add this
        return redirect(self.success_url)


class AdDeleteView(OwnerDeleteView):
    model = Ad
    

def stream_file(request, pk):
    ad = get_object_or_404(Ad, id=pk)
    response = HttpResponse()
    response['Content-Type'] = ad.content_type
    response['Content-Length'] = len(ad.picture)
    response.write(ad.picture)
    return response

class CommentCreateView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        f = get_object_or_404(Ad, id=pk)
        comment = Comment(text=request.POST['comment'], owner=request.user, ad=f)
        comment.save()
        return redirect(reverse('ads:ad_detail', args=[pk]))

class CommentDeleteView(OwnerDeleteView):
    model = Comment
    template_name = "ads/comment_delete.html"

    # https://stackoverflow.com/questions/26290415/deleteview-with-a-dynamic-success-url-dependent-on-id
    def get_success_url(self):
        ad = self.object.ad
        return reverse('ads:ad_detail', args=[ad.id])
    
# This decorator combination serves two purposes:
# 1. @method_decorator - Converts a function decorator (@csrf_exempt) to be usable on a class-based view
# 2. csrf_exempt - Disables Django's CSRF protection for this view
#    - CSRF (Cross-Site Request Forgery) protection is normally required for POST requests
#    - We disable it here because this view might be called from JavaScript/AJAX requests
#    - name='dispatch' indicates that the decorator should be applied to the dispatch() method    
@method_decorator(csrf_exempt, name='dispatch')
class AddFavoriteView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        print("Add PK",pk)
        # Get the Ad object with the specified primary key, or return 404 if not found
        t = get_object_or_404(Ad, id=pk)
        # Create a new Favorite (Fav) object linking the current user and the ad
        fav = Fav(user=request.user, ad=t)
        try:
            # Attempt to save the favorite to the database
            # The save() operation might fail if this combination of user and ad already exists
            fav.save()  # In case of duplicate key
        except IntegrityError:
            # If a duplicate key error occurs (user has already favorited this ad)
            # silently ignore the error and continue
            pass
        # Return an empty HTTP response to indicate the operation completed
        return HttpResponse()


@method_decorator(csrf_exempt, name='dispatch')
class DeleteFavoriteView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        print("Delete PK",pk) 
        # Get the Ad object with the specified primary key, or return 404 if not found
        t = get_object_or_404(Ad, id=pk)
        
        try:
            # Attempt to find and delete the Favorite entry that matches both the current user and ad
            # If found, the .delete() method will remove it from the database
            Fav.objects.get(user=request.user, ad=t).delete()
        except Fav.DoesNotExist:
            # If no matching Favorite entry exists, silently ignore the error
            # This prevents errors when trying to delete a non-existent favorite
            pass

        # Return an empty HTTP response to indicate the operation completed
        return HttpResponse()

mysite/ads/templates/ads/ad_confirm_delete.html
{% extends "base_menu.html" %}
{% block content %}
  <h1>Delete Ad</h1>
  <p>Are you sure you want to delete the ad: {{ ad }}?</p>
  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes, delete.">
  </form>
{% endblock %}

mysite/ads/templates/ads/ad_detail.html
{% extends "base_menu.html" %}
{% load humanize %}
<!-- https://docs.djangoproject.com/en/4.2/ref/contrib/humanize -->
{% block head %}
    <style>
    .overlay {
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        z-index: 10;
        display: none;
        background-color: rgba(0, 0, 0, 0.5);
        /*dim the background*/
    }
    </style>
{% endblock %}
{% block content %}
    {% if ad.content_type %}
        <div id="overlay"
             class="overlay"
             style="text-align: center"
             onclick="document.getElementById('overlay').style.display = 'none';">
            <img style="width:90%;
                        margin-top: 50px;
                        border:3px solid black"
                 src="{% url 'ads:ad_picture' ad.id %}">
        </div>
    {% endif %}
    <span style="float: right;">
        ({{ ad.updated_at|naturaltime }})
        {% if ad.owner == user %}
            <a href="{% url 'ads:ad_update' ad.id %}"><i class="fa fa-pencil"></i></a>
            <a href="{% url 'ads:ad_delete' ad.id %}"><i class="fa fa-trash"></i></a>
        {% endif %}
    </span>
    {% if ad.content_type %}
        <img style="float:right;
                    max-width:50%"
             src="{% url 'ads:ad_picture' ad.id %}"
             onclick="document.getElementById('overlay').style.display = 'block';">
    {% endif %}
    <h1>
        {% if forum.owner == user %}
            <span style="float: right;">
                <a href="{% url 'ads:ads_update' forum.id %}"><i class="fa fa-pencil"></i></a>
                <a href="{% url 'ads:ads_delete' forum.id %}"><i class="fa fa-trash"></i></a>
            </span>
        {% endif %}
        {{ ad.title }}
    </h1>
    <p>{{ ad.text }}</p>
    {% if ad.tags.all %}
        <p>
            Tags:
            {% for tag in ad.tags.all %}
                <span style="border:1px grey solid; background-color: LightGreen;">{{ tag }}</span>
            {% endfor %}
        </p>
    {% endif %}
</p>
<p>Price: ${{ ad.price }}</p>
{% if user.is_authenticated %}
    <br clear="all" />
    <p>
        {% load crispy_forms_tags %}
        <form method="post" action="{% url 'ads:ad_comment_create' ad.id %}">
            {% csrf_token %}
            {{ comment_form|crispy }}
            <input type="submit" value="Submit">
            <input type="submit"
                   value="All Ads"
                   onclick="window.location.href='{% url 'ads:all' %}';return false;">
        </form>
    </p>
{% endif %}
{% for comment in comments %}
    <p>
        {{ comment.text }}
        ({{ comment.updated_at|naturaltime }})
        {% if user == comment.owner %}
            <a href="{% url 'ads:ad_comment_delete' comment.id %}"><i class="fa fa-trash"></i></a>
        {% endif %}
    </p>
{% endfor %}
<p>
    <a href="{% url 'ads:all' %}">All ads</a>
</p>
{% endblock %}

mysite/ads/templates/ads/ad_form.html
<!-- Form to create a new ad -->
{% extends "base_menu.html" %}
{% load crispy_forms_tags %}
{% block content %}
  <p>
    <form action=""
          method="post"
          id="upload_form"
          enctype="multipart/form-data">
      {% csrf_token %}
      {{ form|crispy }}
      <input type="submit" value="Submit">
      <input type="submit"
             value="Cancel"
             onclick="window.location.href='{% url 'ads:all' %}';return false;">
    </form>
  </p>
  <!-- https://stackoverflow.com/questions/2472422/django-file-upload-size-limit -->
  <script>
  document.getElementById("upload_form").addEventListener("submit", function () {
    console.log('Checking file size');
    if (window.File && window.FileReader && window.FileList && window.Blob) {
      var file = document.getElementById('id_{{ form.upload_field_name }}').files[0];
      if (file && file.size > {{ form.max_upload_limit }}) {
        alert("File " + file.name + " of type " + file.type + " must be < {{ form.max_upload_limit_text }}");
        return false;
      }
    }
  });
  </script>
{% endblock %}

mysite/ads/templates/ads/ad_list.html
<!-- Initial screen that shows all the ads -->
{% extends "base_menu.html" %}
{% block content %}
  <!-- Creates a search box floting to the right that sends a get request to the same page with the search query as a parameter -->
  <div style="float:right">
    <!-- https://www.w3schools.com/howto/howto_css_search_button.asp -->
    <form>
      <input type="text"
             placeholder="Search.."
             name="search"
             {% if search %}value="{{ search }}"{% endif %}>
      <button type="submit">
        <i class="fa fa-search"></i>
      </button>
      <a href="{% url 'ads:all' %}"><i class="fa fa-undo"></i></a>
    </form>
  </div>
  <h1>Ads App Landing Page</h1>
  <br />
  <h2>All Ads</h2>
  <p>
    {% if ad_list %}
      <ul>
        {% for ad in ad_list %}
          <li>
            <a href="{% url 'ads:ad_detail' ad.id %}">{{ ad.title }}</a>
            <!-- Check if the current user is the owner of this ad -->
            {% if ad.owner == user %}
              (
              <!-- If user is owner, show an Edit link that goes to the ad_update view with this ad's ID -->
              <a href="{% url 'ads:ad_update' ad.id %}">Edit</a> |
              <!-- Also show a Delete link that goes to the ad_delete view with this ad's ID -->
              <a href="{% url 'ads:ad_delete' ad.id %}">Delete</a>
              )
            {% endif %}
            <!-- If the user is authenticated, show the favorite/unfavorite stars -->
            <!-- The two hrefs are stacked on top of each other, with one showing and one hidden -->
            <!-- The JavaScript function favPost() is called when the user clicks on one of the hrefs -->
            <!-- The function takes two arguments: the URL to call, and the ad ID -->
            {% if user.is_authenticated %}
              <!-- Two hrefs with two stacked icons each - one showing and one hidden -->
              <!-- The first href -->
              <!-- Displayed if the ad is an owner's favorite. If clicked, it will call the ad_unfavorite view -->
              <!-- As usual, urls are defined in urls.py and views are defined in views.py -->
              <a href="#"
                 onclick="favPost('{% url 'ads:ad_unfavorite' ad.id %}', {{ ad.id }} );return false;"
                 {% if ad.id not in favorites %}style="display: none;"{% endif %}
                 id="favorite_star_{{ ad.id }}">
                <span class="fa-stack" style="vertical-align: middle;">
                  <i class="fa fa-star fa-stack-1x" style="color: orange;"></i>
                  <i class="fa fa-star-o fa-stack-1x"></i>
                </span>
              </a>
              <!-- the second href -->
              <a href="#"
                 onclick="favPost('{% url 'ads:ad_favorite' ad.id %}', {{ ad.id }} );return false;"
                 {% if ad.id in favorites %}style="display: none;"{% endif %}
                 id="unfavorite_star_{{ ad.id }}">
                <span class="fa-stack" style="vertical-align: middle;">
                  <i class="fa fa-star fa-stack-1x" style="display: none; color: orange;"></i>
                  <i class="fa fa-star-o fa-stack-1x"></i>
                </span>
              </a>
            {% endif %}
          </li>
        {% endfor %}
      </ul>
    {% else %}
      <p>There are no ads in the database.</p>
    {% endif %}
  </p>
</br>
<p>
  <!-- Link to add a new ad. Goes to the ad_create view defined in urls.py -->
  <a href="{% url 'ads:ad_create' %}">Add an Ad</a> &nbsp; &nbsp;   |  &nbsp; &nbsp;
  {% if user.is_authenticated %}
    <a href="{% url 'logout' %}?next={% url 'ads:all' %}">Logout</a>
  {% else %}
     <!-- Link to login. Takes us to the login view in django.contrib.auth with the parameter -->
      <!-- 'next' set to the URL to return to after a successful login -->
    <a href="{% url 'login' %}?next={% url 'ads:all' %}">Login</a>
  {% endif %}
</p>
</br>
</br>
</br>
<!-- Back to home -->
<p>
  <a href="{% url 'home:home' %}">Back to Main Page</a>
</p>
<script>
  // Function to toggle the display of favorite/unfavorite stars
  // Takes the ID of the star element as a parameter
  function toggleInlineDisplay(star_id) {
    // Get the star element by its ID
    var elem = document.getElementById(star_id);

    // If the element is currently displayed inline
    if (window.getComputedStyle(elem).display == "inline") {
      // Hide it and store that it was previously inline
      elem.style.display = 'none';
      elem.dataset.previousDisplay = 'inline';
    } 
    // If the element is currently displayed as a block
    else if (window.getComputedStyle(elem).display == "block") {
      // Hide it and store that it was previously block
      elem.style.display = 'none';
      elem.dataset.previousDisplay = 'block';
    }
    // If the element is currently hidden
    else {
      // Log the previous display value for debugging
      console.log('prev', elem.dataset.previousDisplay);
      // If we stored a previous display value
      if (typeof elem.dataset.previousDisplay == 'string') {
        // Restore that previous display value
        elem.style.display = elem.dataset.previousDisplay
      } else {
        // Default to inline display if no previous value
        elem.style.display = 'inline';
      }
    }
  }

  // Function that handles favoriting/unfavoriting posts
  // Takes a URL (favorite or unfavorite endpoint) and the ad's ID as parameters
  function favPost(url, ad_id) {
    // Log the URL being called to the console for debugging
    console.log('POSTing to', url);
    
    // Make a POST request to the provided URL with an empty JSON body
    fetch(url, { method: 'POST', body: '{}' })
      .then((response) => {
        // Log when the request is complete
        console.log(url, 'finished');
        
        // Toggle the visibility of both the favorite and unfavorite stars
        // This switches which star icon is visible to the user
        toggleInlineDisplay("unfavorite_star_" + ad_id);
        toggleInlineDisplay("favorite_star_" + ad_id);
      })
      .catch((error) => {
        // If the request fails, show an alert with the error message
        alert('Url failed with ' + error + ' ' + url);
      });
  }
</script>
{% endblock %}

mysite/ads/templates/ads/comment_delete.html
{% extends "base_bootstrap.html" %}
{% block content %}
  <h1>Delete Comment</h1>
  <p>Are you sure you want to delete</p>
  <p>{{ comment.text }}?</p>
  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit"  class="btn btn-primary" value="Yes, delete.">
    <a href="{% url 'ads:ad_detail' comment.ad.id %}"
       class="btn btn-secondary">Cancel</a>
  </form>
{% endblock %}